name: Trading Bot 15m

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install requests

      - name: Run Bot
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_SECRET_KEY: ${{ secrets.MEXC_SECRET_KEY }}
        run: python bot.py
